name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      CI: 1
      EXPO_NO_INTERACTIVE: 1

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g eas-cli
        npx expo install --fix

    - name: Run ESLint
      run: |
        npm install eslint eslint-plugin-react eslint-plugin-react-native --save-dev
        npx eslint . --ext .js,.jsx

    - name: Setup TypeScript
      run: |
        npm install --save-dev typescript @types/react @types/react-native @types/jest
        npm install --save-dev @babel/preset-typescript

    - name: Run Tests
      run: npm test -- --passWithNoTests

    - name: Login to Expo
      run: npx eas-cli login --non-interactive --token ${{ secrets.EXPO_TOKEN }}

    - name: Build Android Preview
      run: npx eas build --platform android --profile preview --non-interactive --no-wait

    - name: Build iOS Preview
      if: runner.os == 'macOS'
      run: npx eas build --platform ios --profile preview --non-interactive --no-wait

    - name: Post Setup Node.js
      run: echo "Build submitted to EAS" 